### PR TITLE
log errors from browserscope instead of rejecting

### LINKED ISSUE #257: “Unexpected response from browserscope.org” shouldn’t prevent new test creation
Whenever the “Unexpected response from browserscope.org” occurs, jsPerf should still create the test, just without a Browserscope ID.

When the test page is accessed we can re-attempt to get a Browserscope ID for this test.

### PR DESCRIPTION
**Pull request by maxbeatty**
fixes #257

### CODE REVIEW

File: server/repositories/browserscope.js [hunk 1]
```diff
@@ -22,10 +22,14 @@ exports.register = function (server, options, next) {
           try {
             resolve(JSON.parse(str).test_key);
           } catch (e) {
-            reject(new Error('Unexpected response from browserscope.org'));
+            server.log('error', e);
```
Comment (mathiasbynens) [inline server/repositories/browserscope.js]: I like to avoid single-letter variable names, like `exception` instead of `e`. WDYT about that?

Comment (maxbeatty) [inline server/repositories/browserscope.js]: I've been writing a lot of Go lately which has me in the short variable name habbit 😸 

> Variable names in Go should be short rather than long. This is especially true for local variables with limited scope. Prefer c to lineCount. Prefer i to sliceIndex.
> – [Go Code Review](https://github.com/golang/go/wiki/CodeReviewComments#variable-names)

Looks like [ESLint could help](http://eslint.org/docs/rules/id-length) me when writing JS
